FROM node:16-alpine as builder
WORKDIR /usr/app
COPY . .
RUN yarn && yarn build

FROM nginx:stable-alpine as runner
COPY --from=builder /usr/app/out /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
