FROM node:16-alpine as base

FROM base as builder
WORKDIR /usr/app
COPY . .
RUN yarn && yarn build

FROM base as runner
WORKDIR /usr/app
COPY --from=builder /usr/app/public ./public
COPY --from=builder /usr/app/.next/standalone .
COPY --from=builder /usr/app/.next/static .next/static
RUN yarn
EXPOSE 3000
ENTRYPOINT node server.js
